name: blog-service
on:
  push:
    branches:
      - main

env:
  ## Sets environment variable
  OS: ubuntu-latest

jobs:

  docker-login:
    name: Login
    runs-on: ${{ env.OS }}
    steps:
      - name: 'Azure CLI Login'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: 'Docker Login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
